[build-system]
requires = ["setuptools>=60.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ft_package"
version = "0.0.1"
description = "A simple test package"
readme = "README.md"
authors = [
    { name = "rwassim", email = "rwassim@student.42.fr" }
]
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux"
]
requires-python = ">=3.10"
[project.urls]
Homepage = "https://github.com/mossfreestyle/mossfreestyle"
